3.2.0 CLI Release notes
purduesigbots/pros-docs pull request #225
Opened 2021-02-18 03:29 UTC by WillXuCodes

- Created CLI Release Notes
- Updated mentions of prosv5 to pros where applicable.

2021-02-25 00:40 UTC, kunwarsahni01 approved these changes

2021-02-28 22:31 UTC, HotelCalifornia requested changes
did we release 3.1.4 or 3.2.0? because the release notes say 3.1.4.

also the windows installers are still broken (beyond repair?) so idk when we're gonna be able to actually get that out

2021-03-19 05:46 UTC, HotelCalifornia requested changes

2021-03-19 05:46 UTC, HotelCalifornia commented on v5/releases/cli3.2.0.rst
> +Run ``pip install https://github.com/purduesigbots/pros-cli/releases/download/3.2.0/pros_cli_v5-3.2.0-py3-none-any.whl`` (or pip3, depending on your system)
```suggestion
Run ``pip install --upgrade pros-cli` (or pip3, depending on your system)
```

2021-03-19 05:53 UTC, HotelCalifornia commented on v5/getting-started/linux.rst
>  2. Check the latest version of the PROS CLI on `our releases page <https://github.com/purduesigbots/pros-cli3/releases/latest>`_, and run :code:`python3.6 -m pip install --user https://github.com/pur
```suggestion
2. Install the latest version of the PROS CLI from the Python Package Index, using :code:`python3 -m pip install --user pros-cli`. If you wish to install for all users, run the command with :code:`sudo` and remove the :code:`--user` flag.
```

2021-03-19 05:54 UTC, HotelCalifornia commented on v5/releases/cli3.2.0.rst
> +
add "compatible with vexOS 1.0.13"

2021-03-19 06:02 UTC, HotelCalifornia requested changes

2021-03-19 06:02 UTC, HotelCalifornia commented on v5/releases/cli3.2.0.rst
> +If you have the editor installed, you can also run ``brew cask upgrade pros-editor``.
```suggestion
If you have the editor installed, you can also run ``brew upgrade pros-editor``.
```
i think the unification means you can just do this now

2021-03-19 06:02 UTC, HotelCalifornia commented on v5/releases/cli3.2.0.rst
> +Run ``brew install gcc-arm-bin && brew cask install pros-editor`` (if you want to install only the CLI, you can run ``brew install gcc-arm-bin pros-cli`` instead)
```suggestion
Run ``brew install gcc-arm-bin && brew --cask install pros-editor`` (if you want to install only the CLI, you can run ``brew install gcc-arm-bin pros-cli`` instead)
```

2021-03-19 06:02 UTC, HotelCalifornia commented on v5/releases/cli3.2.0.rst
> +- if you installed using the .app bundle, you can move that bundle to the trash folder, and then run ``rm -f /usr/local/bin/prosv5`` to clear out the old file
these were more pertinent when i could reasonably expect people to have old, non-homebrew installs. by-and-large this is no longer the case

2021-03-19 06:14 UTC, HotelCalifornia commented on v5/releases/cli3.2.0.rst
> +Run ``brew install gcc-arm-bin && brew --cask install pros-editor`` (if you want to install only the CLI, you can run ``brew install gcc-arm-bin pros-cli`` instead)
```suggestion
If you are installing for the first time, see `the getting started guide for macOS <https://pros.cs.purdue.edu/v5/getting-started/macos.html>` for instructions.
```

2021-03-19 06:23 UTC, HotelCalifornia approved these changes

2021-03-19 06:24 UTC, merged